name: Build WebGPUReconstruct
on:
  workflow_call:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: windows
            backend: dawn
            os: windows-latest

          - platform: windows
            backend: wgpu
            os: windows-latest

          - platform: linux
            backend: dawn
            os: ubuntu-latest

          - platform: linux
            backend: wgpu
            os: ubuntu-latest

          - platform: android
            backend: wgpu
            os: windows-latest

          - platform: android
            backend: dawn
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Build release build
        uses: ./.github/actions/build
        with:
          platform: ${{ matrix.platform }}
          backend: ${{ matrix.backend }}

      - name: Upload build artifacts
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: ./.github/actions/upload
        with:
          platform: ${{ matrix.platform }}
          backend: ${{ matrix.backend }}

  merge:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Merge builds and release
        uses: ./.github/actions/release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}