name: Build WebGPUReconstruct
on:
  workflow_call:
  push:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: windows
            backend: dawn
            os: windows-latest

          - platform: windows
            backend: wgpu
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: WebGPUReconstruct Release Build
        uses: ./.github/actions/build
        with:
          backend: ${{ matrix.backend }}

      - name: WebGPUReconstruct Upload Build
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: ./.github/actions/upload
        with:
          platform: ${{ matrix.platform }}
          backend: ${{ matrix.backend }}